version: "3.8"

services:
  postgres-service:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ping_service
    ports:
      - "5432:5432"
    volumes:
      - ./backend/scripts/create_tabel.sql:/docker-entrypoint-initdb.d/create_tabel.sql

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres-service
    restart: on-failure